### ISSUE TITLE
Usage with StyleResources

### ISSUE THREAD

**Issue by nachogarcia** [nuxt-community/stylelint-module#37]
Hello, I've tried to use this module alongside [Nuxt Style Resources module](https://github.com/nuxt-community/style-resources-module) and I haven't been able to get stylelint to have the context of the common files. Can I get any insights?

Also, i havent been able to easily have a setup for my nuxt project because it also fails with errors like `Unexpected unknown pseudo-element selector "::v-deep"`.
I don't really know if it's because of my .stylelintrc file, since there is no default option with a base that works for most and serve as a base (it would be great).

**Comment by ricardogobbosouza** [comment]
Hi @nachogarcia 
Could you provide a repository to reproduce?

**Comment by defaye** [comment]
https://github.com/chrisvfritz/vue-enterprise-boilerplate/issues/190 the problem is indeed with stylelint
