### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by liyasthomas** [nuxt-community/stylelint-module#43]
Nuxt project produce the following error on development mode.

![image](https://user-images.githubusercontent.com/10395817/83268959-ffd4b680-a1e3-11ea-814a-c24cd40ec11d.png)

@nuxtjs/stylelint-module: `v4.0.0`

> Which rule, if any, is the bug related to?

default/no rules needed

> What code is needed to reproduce the bug?

can't detect from where the error originated.

> What stylelint configuration is needed to reproduce the bug?

default config

> Which version of stylelint are you using?

`v13.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

"*.{scss,css,vue}": "stylelint"

`lint-staged` on pre-commit along with nuxt-stylelint-module

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

not sure

> What did you expect to happen?

No stylelint error

> What actually happened (e.g. what warnings or errors did you get)?

e.g. "The following warnings were flagged:"

Nuxt project produce the following error on development mode.
```
ERROR StylelintError

The "path" argument must be of type string. Received type undefined
```

**Comment by ricardogobbosouza** [comment]
Hi @liyasthomas 
Could you provide a repository to reproduce the problem?

**Comment by liyasthomas** [comment]
Mine is a private repo. Let double check whether it has an issue with any of my imports or configs or else I'll try to reproduce the issue in a bare clone.

**Comment by liyasthomas** [comment]
Fresh clone of repo couldn't reproduce the issue.
