### ISSUE TITLE
Hey, about the "Nuxt < 2.9" are we referring to "2.9 and bellow" or "2.9 and above"?

### ISSUE THREAD

**Issue by vhoyer** [nuxt-community/stylelint-module#47]
https://github.com/nuxt-community/stylelint-module/blame/master/README.md#L43

**Comment by ricardogobbosouza** [comment]
Hi @vhoyer,
Sorry for the late reply
As the documentation says, below 2.9.

**Comment by vhoyer** [comment]
Sorry for the stupid question, I just wasn't sure when I read it

**Comment by ricardogobbosouza** [comment]
No problem, `buildModules` added in https://github.com/nuxt/nuxt.js/releases/tag/v2.9.0
