### ISSUE TITLE
How to setup Vue + ESlint + Prettier + Stylelint ?

### ISSUE THREAD

**Issue by kissu** [nuxt-community/stylelint-module#50]
Hi ! 👋🏻 

I have setup the whole thing through the `nuxt CLI` when creating a new app.

I've tried several things this afternoon to try to achieve that kind of workflow:
- working in my `.vue` files and having ESlint running
- getting my `<script>` formatted by Prettier
- getting my `CSS`/`SCSS` linted + formatted by Stylelint

My configuration is perfectly working with ESlint + Prettier. But I could not have Stylelint working with only `ESlint` installed as a VScode plugin.

Annoying because I was trying to setup the whole project having my buddies to run VScode. So, I kinda gave up on that one and went the more easy way..

Then, I installed the `Stylelint` plugin and got my code _kinda_ working. I now do have collisions between Prettier and Stylelint.

Here is my `stylelint.config.js`:
```js
module.exports = {
  extends: ['stylelint-config-standard', 'stylelint-config-prettier'],
  rules: {
    'color-hex-case': 'upper', // this is the test rule
  },
}
```

`stylelint-config-prettier-check` tells me
> Conflicting rule(s) detected in your stylelint configuration:
color-hex-case

So, basically when I go to a random `.vue` file, and write
```js
<style>
.test {
  color: #ddd;
}
</style>
```

Stylelint does his job but have conflicts with Prettier even if extended the Stylelint config with `stylelint-config-prettier`.
![image](https://user-images.githubusercontent.com/5133074/96895317-9738ef80-148c-11eb-830d-db5518a983d7.png)

Here is a copy of my most relevant settings I do have (`settings.json`):
```json
{
  "editor.formatOnPaste": true,
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 500,
  "editor.codeActionsOnSave": {
    "source.fixAll": false,
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true
  },

  "eslint.run": "onSave",
  "eslint.options": {
    "extensions": [
      ".html",
      ".js",
      ".vue",
      ".jsx"
    ]
  },
  "eslint.probe": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue",
    "markdown"
  ],

  "vetur.format.defaultFormatter.js": "prettier",
  "vetur.format.defaultFormatter.css": "none",
  "vetur.format.defaultFormatter.less": "none",
  "vetur.format.defaultFormatter.postcss": "prettier",
  "vetur.format.defaultFormatter.scss": "none",
  "vetur.format.defaultFormatter.html": "prettier",
  "vetur.validation.style": true,
  "javascript.validate.enable": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue"
  ],

  "css.validate": false,
  "less.validate": false,
  "scss.validate": false,
  "stylelint.enable": true,
  "editor.formatOnSave": true,
  "javascript.format.enable": true,
  "editor.formatOnType": true,
  "vetur.validation.template": false
}
```

I have to admit that I'm pretty lost between all the various settings.
I've tried to follow [Prettier stylelint-integration](https://prettier.io/docs/en/related-projects.html#stylelint-integrations) and [Prettier integrating with linter](https://prettier.io/docs/en/integrating-with-linters.html#docsNav) but none of them worked.

Could you please explain me why and how I could fix this issue: do not have the conflict between Prettier and Stylelint. 🙏🏻

**Comment by ricardogobbosouza** [comment]
I intend to look at this by the end of the month
Sorry for the delay @kissu

**Comment by kissu** [comment]
Hey ! 👋🏻 
I'm actually working w/ Nuxt and using `@nuxtjs/stylelint-module` wo/ any issues so far ! 🎊
The next time I may change my configuration, it may be w/ Vue3 or Nuxt (w/ Vue3), so even if I wished to make it work then, now I'm fine.

I'd rather be clear and don't make you waste your time for something I'd maybe never try to make work. If you have some time for it (in case somebody else in the community have the same question), feel free.

But as for now, I guess that I can close this issue. Thanks for your time both of you. ❤️
