### ISSUE TITLE
No files matching the pattern (Again, with 3.2.2)

### ISSUE THREAD

**Issue by qmolab** [nuxt-community/stylelint-module#59]
'No files matching the pattern "[project path]/**/*.{s?(a|c)ss,less,stylus}, [project path]/{components,layouts,pages}/**/*.vue" were found.'

There are in fact both stylesheets and vue files at the locations specified. I am using 
    "nuxt": "^2.15.8",
    "@nuxtjs/stylelint-module": "^3.2.2",
    "stylelint": "^14.0.0",

This is the exact same error a bunch of other people got, but with older versions of the packages. According to everything I can find, these errors only existed for lower version numbers, so I cannot figure out why it is still happening to me even though I have updated everything. Thanks!

**Comment by ricardogobbosouza** [comment]
Hi @qmolab 
Try the version [v4.1.0](https://github.com/nuxt-community/stylelint-module/commit/e2fe4db4b92829c254758b5da7adb32b477bafb1)

**Comment by baixiaoyu2997** [comment]
@ricardogobbosouza  hi, i think i have same issue, can find in [here](https://codesandbox.io/s/dp9oy?file=/package.json) 
page not have error ,but ,when run `yarn lint:style`, u can find error in `assets/global.css` file :
```
 Unexpected browser feature "css-sticky" is not       plugin/no-unsupported-browser-features
         supported by IE 11, Opera Mini all, Baidu Browser
         7.12 and only partially supported by Opera
         80,81,82, UC Browser for Android 12.12, QQ Browser
         10.4, KaiOS Browser 2.5
```
