### ISSUE TITLE
Update peer dependancy of stylelint to 14+

### ISSUE THREAD

**Issue by miroslavgeorgiev** [nuxt-community/stylelint-module#60]
When updated stylelint to v14+, Im getting this error while trying to run the app so I had to downgrade again to stylelint v13:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@1.0.0
npm ERR! Found: stylelint@14.0.0
npm ERR! node_modules/stylelint
npm ERR!   dev stylelint@"^14.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer stylelint@"^13.0.0" from @nuxtjs/stylelint-module@4.0.0
npm ERR! node_modules/@nuxtjs/stylelint-module
npm ERR!   dev @nuxtjs/stylelint-module@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

Do you consider updating the peer dependacy of stylelint to v14+/latest to ensure no problems will apear when updating to the newest version of stylelint?

**Comment by miroslavgeorgiev** [comment]
@ricardogobbosouza - any thoughts on this?
Can you update the peer deps so this doesn't break on stylelint 14+?

**Comment by monsieurnebo** [comment]
Same issue over here 💥 

It would be great to add the stylelint v14 support.

**Comment by ricardogobbosouza** [comment]
Hi @miroslavgeorgiev, @monsieurnebo 
Sorry for the delay
Added support for stylelint v14 in version [v4.1.0](https://github.com/nuxt-community/stylelint-module/commit/e2fe4db4b92829c254758b5da7adb32b477bafb1)

**Comment by miroslavgeorgiev** [comment]
@ricardogobbosouza - Great! Thanks 👍

**Comment by monsieurnebo** [comment]
Thanks @ricardogobbosouza 👌
