### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by HelloAlexPan** [nuxt-community/stylelint-module#63]
Opening an issue to discuss whether there's plans to support Nuxt 3 and how the community can help.

**Comment by nestle49** [comment]
What's up guys?

**Comment by Saran010** [comment]
Any news?

**Comment by szulcus** [comment]
https://www.npmjs.com/package/vite-plugin-stylelint ;)

**Comment by avinean** [comment]
Any news?

**Comment by legostud** [comment]
I'm going to be starting a new Project with Nuxt3 and I was hoping to use this tool, but it doesn't seem to work correctly.  Any updates on creating a Nuxt 3 version?

**Comment by Neosoulink** [comment]
👀 Any news???

**Comment by szulcus** [comment]
It's been more than half a year and there is still silence. Why don't you just use the Vite plugin that is being developed regularly?

**Comment by ricardogobbosouza** [comment]
Release [v.5.0.0](https://github.com/nuxt-community/stylelint-module/releases/tag/v5.0.0)
